### PR TITLE
Create MySQL RESTBase backend

### PR DESCRIPTION
**Pull request by lens0021**
Bug: https://phabricator.wikimedia.org/T147991

### CODE REVIEW

**Comment by d00rman** [comment]
Merged. Apologies it took so long @lens0021 . Could you please add @Pchelolo and myself to the list of the package's contributors on npmjs?

**Comment by lens0021** [comment]
@d00rman Yes, I could do it soon. But I am wondering if you could also add me and my team member, @simnalamburt to this repository as collaborators. I think there is room for improvement in my codes and simnalamburt is planning to introduce modern Libraries such as TypeScript. 

This module is very important for my team working on managing a wiki hosted in [https://femiwiki.com](https://femiwiki.com). We had a hard time running RESTBase with Cassandra or SQLite, asked for advice on the Technical Advice IRC meeting and has decided to implement it ourselves. Maybe we could use and manage a fork of RESTBase, but I think that is a bad idea for us when I think about the Open Source Ecosystem.

Best regards.

**Comment by simnalamburt** [comment]
@d00rman We are strongly committed to developing and maintaining a restbase-mod-table-mysql project. We think our collaboration will generate a lot of synergy. We wish we could develop together.

**Comment by d00rman** [comment]
ok @lens0021 @simnalamburt added you both to the repo as maintainers, you should have an invite in your inboxes.

**Comment by simnalamburt** [comment]
Thanks! We've invited you to the npm repo too :)

2019년 11월 4일 (월) 오후 9:44, Marko Obrovac <notifications@github.com>님이 작성:

**Pull request merged**
